# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running shared tests..."
      - go test
  lint:
    cmds:
      - echo "Running shared linters..."
      - golangci-lint run