# Add labels based on file patterns

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - '**/doc.go'

github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - 'test/**'
          - 'internal/testutils/**'

# Core components
composer:
  - changed-files:
      - any-glob-to-any-file: 'pkg/composer/**'

connection:
  - changed-files:
      - any-glob-to-any-file: 'pkg/connection/**'

commands:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/**'

document:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/**'

graphics:
  - changed-files:
      - any-glob-to-any-file: 'pkg/graphics/**'

profile:
  - changed-files:
      - any-glob-to-any-file: 'pkg/profile/**'

service:
  - changed-files:
      - any-glob-to-any-file: 'pkg/service/**'

# ESC/POS specific components
barcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/escpos/barcode/**'

qrcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/escpos/qrcode/**'

bitimage:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/escpos/bitimage/**'

character:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/escpos/character/**'

# Other categories
windows:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_windows.go'
          - 'pkg/connection/windows/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'go.mod'
          - 'go.sum'
          - 'package.json'
          - 'package-lock.json'