# Configuración simple pero efectiva para proyecto personal/pequeño
version: "2"
run:
  timeout: 5m  # 5 minutos es suficiente
  tests: true
  build-tags:
    - integration

linters:
  # Solo habilitar los esenciales
  enable:
    # Critical linters
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec
    - unused

    # Code quality
    - gocyclo
    - gocritic
    - unparam
    - revive
    - misspell

    # Best practices
    - prealloc
    - bodyclose
    - goconst