# https://taskfile.dev

version: '3'

vars:
  GP_TEST_FLAGS: -v
  LINT_FLAGS: --timeout=5m
  BANNER: |
    ╔══════════════════════════════════════════════════════════╗
    ║                                                          ║
    ║   ██████╗  ██████╗ ███████╗████████╗███████╗██████╗      ║
    ║   ██╔══██╗██╔═══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗     ║
    ║   ██████╔╝██║   ██║███████╗   ██║   █████╗  ██████╔╝     ║
    ║   ██╔═══╝ ██║   ██║╚════██║   ██║   ██╔══╝  ██╔══██╗     ║
    ║   ██║     ╚██████╔╝███████║   ██║   ███████╗██║  ██║     ║
    ║   ╚═╝      ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝     ║
    ║                                                          ║
    ║                  The POS daemon for Go                   ║
    ║                  ESCPOS · ZPL · Scale                    ║
    ║           Serial · USB · Network · Bluetooth             ║
    ║                                                          ║
    ╚══════════════════════════════════════════════════════════╝

includes:
  barcode:
    taskfile: ./pkg/controllers/escpos/barcode/Taskfile.yml
    dir: ./pkg/controllers/escpos/barcode
    aliases:
      - bc
  bitimage:
    taskfile: ./pkg/controllers/escpos/bitimage/Taskfile.yml
    dir: ./pkg/controllers/escpos/bitimage
    aliases:
      - bi
  character:
    taskfile: ./pkg/controllers/escpos/character/Taskfile.yml
    dir: ./pkg/controllers/escpos/character
    aliases:
      - ch
  linespacing:
    taskfile: ./pkg/controllers/escpos/linespacing/Taskfile.yml
    dir: ./pkg/controllers/escpos/linespacing
    aliases:
      - ls
  mechanismcontrol:
    taskfile: ./pkg/controllers/escpos/mechanismcontrol/Taskfile.yml
    dir: ./pkg/controllers/escpos/mechanismcontrol
    aliases:
      - mc
  print:
    taskfile: ./pkg/controllers/escpos/print/Taskfile.yml
    dir: ./pkg/controllers/escpos/print
    aliases:
      - pr
  printposition:
    taskfile: ./pkg/controllers/escpos/printposition/Taskfile.yml
    dir: ./pkg/controllers/escpos/printposition
    aliases:
      - pp
  qrcode:
    taskfile: ./pkg/controllers/escpos/qrcode/Taskfile.yml
    dir: ./pkg/controllers/escpos/qrcode
    aliases:
      - qr
  shared:
    taskfile: ./pkg/controllers/escpos/shared/Taskfile.yml
    dir: ./pkg/controllers/escpos/shared
    aliases:
      - sh
  integration-tests:
    taskfile: ./test/Taskfile.yml
    dir: ./test
    aliases:
      - itest
tasks:
  default:
    cmds:
      - echo "{{.BANNER}}"
    silent: true
  build:
    deps:
      - test
      - lint
    cmds:
      - echo "Building the project..."
      - go build ./...
  lint:
    cmds:
      - echo "Running linters..."
      - golangci-lint run {{.LINT_FLAGS}}
  test:
    cmds:
      - echo "Running all tests in detail..."
      - go test {{.GP_TEST_FLAGS}} ./...