# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running mechanismcontrol tests..."
      - go test
  lint:
    cmds:
      - echo "Running mechanismcontrol linters..."
      - golangci-lint run