# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running print position tests..."
      - go testutils
  lint:
    cmds:
      - echo "Running print position linters..."
      - golangci-lint run