# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running printposition tests..."
      - go test
  lint:
    cmds:
      - echo "Running printposition linters..."
      - golangci-lint run