# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running mechanism control tests..."
      - go test
  lint:
    cmds:
      - echo "Running mechanism control linters..."
      - golangci-lint run