# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running print tests..."
      - go testutils
  lint:
    cmds:
      - echo "Running print linters..."
      - golangci-lint run