# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running bit image tests..."
      - go test
  lint:
    cmds:
      - echo "Running bit image linters..."
      - golangci-lint run