# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running linespacing tests..."
      - go test
  lint:
    cmds:
      - echo "Running linespacing linters..."
      - golangci-lint run