# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running line spacing tests..."
      - go testutils
  lint:
    cmds:
      - echo "Running line spacing linters..."
      - golangci-lint run