# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running character tests..."
      - go testutils
  lint:
    cmds:
      - echo "Running character linters..."
      - golangci-lint run