# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running barcode tests..."
      - go test
  lint:
    cmds:
      - echo "Running barcode linters..."
      - golangci-lint run